# This workflow will build a package using Maven and then publish it to
#  qbic-repo.qbic.uni-tuebingen.de packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Generate reports

on:
  release:
    types: [created]
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install dependencies
        shell: bash -l {0}
        run: conda create --quiet --yes --channel conda-forge --name qbic-docs-build python=3 pygithub
      - name: Load local Maven repository cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven generate reports
        shell: bash -l {0}
        run: mvn --activate-profiles !development-build,!release-build --settings .github.settings.xml site
      - name: Publish reports
        shell: bash -l {0}
        run: |
          conda activate qbic-docs-build
          python --version
          python $GITHUB_WORKSPACE/.generate-reports.py ${GITHUB_REF##*/} $GITHUB_REPOSITORY "[Github Action] Updated gh-pages"
        env:
          REPORTS_GITHUB_ACCESS_TOKEN: ${{ github.token }}