# This workflow will build a package using Maven and then publish it to
#  qbic-repo.qbic.uni-tuebingen.de packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Generate reports

on:
  release:
    types: [created]
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Install dependencies
        run: .$GITHUB_WORKSPACE/.install-reports-dependencies.sh
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Load conda env
        run: |
          echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc && conda activate qbic-docs-build
          mvn --quiet --activate-profiles !development-build,!release-build --settings .github.settings.xml site
      - name: Generate reports
        run: python $GITHUB_WORKSPACE/generate-reports.py
        env:
          REPORTS_GITHUB_ACCESS_TOKEN: ${{ github.token }}